# Generated by Django 5.1.1 on 2024-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
